name: Terraform CI/CD

on:
  push:
    branches: ['main']

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
  AWS_REGION: us-east-1

jobs:
  provision-infra:
    runs-on: ubuntu-latest
    outputs:
      CLIENT_IP: ${{ steps.set-ip.outputs.client }}
      SERVER_IP: ${{ steps.set-ip.outputs.server }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false
      - name: Format Terraform code
        id: format
        run: terraform fmt
      - name: Terraform Init
        id: init
        run: terraform init
      - name: Terraform Plan
        id: plan
        run: terraform plan
      - name: Terraform Apply
        run: terraform apply --auto-approve
      - name: Terraform Destroy
        run: terraform destroy --auto-approve
  #     - name: Set outputs
  #       id: set-ip
  #       run: |
  #         echo "::set-output name=client::$(terraform output client_admin_ip)"
  #         echo "::set-output name=server::$(terraform output server-ip)"
  #       working-directory: ./

  # deploy_to_server:
  #   runs-on: ubuntu-latest
  #   needs: provision-infra
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #     - name: Set IP env variable
  #       run: |
  #         echo CLIENT_IP=${{ needs.provision-infra.outputs.CLIENT_IP }} >> $GITHUB_ENV
  #         echo SERVER_IP=${{ needs.provision-infra.outputs.SERVER_IP }} >> $GITHUB_ENV
  #     - name: SSH to Server Instance
  #       uses: appleboy/ssh-action@master
  #       with:
  #         host: ${{ env.CLIENT_IP }}
  #         username: ubuntu
  #         key: ${{ env.AWS_PRIVATE_KEY }}
  #         envs: PRIVATE_SSH_KEY,AWS_ACCESS_KEY_ID,AWS_SECRET_ACCESS_KEY
  #         script: |
  #           AWS_PRIVATE_KEY=${{ env.AWS_PRIVATE_KEY }}
  #           echo $AWS_PRIVATE_KEY > webi.pem
  #           chmod 400 webi.pem
  #           ssh -o StrictHostKeyChecking=no -i "webi.pem" ubuntu@${{ env.SERVER_IP }}

  #           echo "----Successfully Login into Server Instance-------"
            
  #           echo "*****************************************************************"
  #           echo "Performing the following actions on Server Instance"
  #           echo "*****************************************************************"  
  #           sudo apt-get update
  #           sudo apt-get install git -y
  #           sudo touch abdulmalik.txt






















            